---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-client
  image: plugins/docker
  settings:
    dockerfile: package/client/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/pushprox-client"
    tag: "${DRONE_TAG}-client-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-proxy
  image: plugins/docker
  settings:
    dockerfile: package/proxy/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/pushprox-proxy"
    tag: "${DRONE_TAG}-proxy-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-client
  image: plugins/docker
  settings:
    dockerfile: package/client/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/pushprox-client"
    tag: "${DRONE_TAG}-client-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-proxy
  image: plugins/docker
  settings:
    dockerfile: package/proxy/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/pushprox-proxy"
    tag: "${DRONE_TAG}-proxy-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-client
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "rancher/pushprox-client:${DRONE_TAG}-client"
    template: "rancher/pushprox-client:${DRONE_TAG}-client-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: manifest-proxy
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "rancher/pushprox-proxy:${DRONE_TAG}-proxy"
    template: "rancher/pushprox-proxy:${DRONE_TAG}-proxy-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- amd64
- arm64
