FROM golang:1.22-alpine3.18 as builder
WORKDIR /usr/src/app
# Install make
RUN apk add --no-cache make
COPY . .
RUN ls -lart ./scripts
RUN make ci

FROM alpine:3.18.6
COPY --from=builder /go/bin/pushprox-client /usr/bin
CMD ["pushprox-client"]