#!/bin/bash
set -e
set -x

cd $(dirname $0)/..

for COMPONENT in proxy client
do
    pushd ./cmd/${COMPONENT}
    echo "Running tests for ${COMPONENT}"
    go test -cover -tags=test ./...
    popd
done